import React, { useState, useEffect } from "react";
import Table from "../../components/layouts/Table";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import "jspdf-autotable";

export default function ERPReportModule() {
  const [filters, setFilters] = useState({
    dateFrom: "",
    dateTo: "",
    department: "All",
    region: "All",
  });

  const [reports] = useState([
    { id: 1, name: "Sales Summary", type: "sales" },
    { id: 2, name: "Inventory Stock", type: "inventory" },
    { id: 3, name: "Profit & Loss", type: "finance" },
  ]);

  const [selectedReport, setSelectedReport] = useState(null);
  const [data, setData] = useState([]);
  const [isRealTime, setIsRealTime] = useState(false);
  const [log, setLog] = useState([]);
  const [schedule, setSchedule] = useState(null);

  const handleFilterChange = (e) => {
    const { name, value } = e.target;
    setFilters((prev) => ({ ...prev, [name]: value }));
  };

  const handleGenerateReport = (report) => {
    setSelectedReport(report);
    generateFakeData(report);
    addLog(`Generated ${report.name} (${filters.department}, ${filters.region})`);
  };

  // ✅ Export as CSV
  const exportCSV = () => {
    if (!selectedReport) return;
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, selectedReport.name);
    XLSX.writeFile(workbook, `${selectedReport.name}.csv`);
    addLog(`Exported ${selectedReport.name} to CSV`);
  };

  // ✅ Export as Excel
  const exportExcel = () => {
    if (!selectedReport) return;
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, selectedReport.name);
    XLSX.writeFile(workbook, `${selectedReport.name}.xlsx`);
    addLog(`Exported ${selectedReport.name} to Excel`);
  };

  // ✅ Fixed Export as PDF
  const exportPDF = () => {
  if (!selectedReport || data.length === 0) {
    alert("Please generate a report before exporting.");
    return;
  }

  const doc = new jsPDF("landscape", "pt", "A4");
  const currentDate = new Date().toLocaleString();
  const reportTitle = `${selectedReport.name} Report`;

  // ✅ Header section
  doc.setFontSize(18);
  doc.text("Enterprise Resource Planning Report", 40, 40);
  doc.setFontSize(14);
  doc.text(reportTitle, 40, 70);
  doc.setFontSize(10);
  doc.text(`Generated on: ${currentDate}`, 40, 90);

  // ✅ Optional metadata — you can link these from state/filters
  const filters = [
    `Date Range: ${selectedDateRange || "N/A"}`,
    `Department: ${selectedDepartment || "All"}`,
    `Region: ${selectedRegion || "All"}`,
  ];

  filters.forEach((filter, index) => {
    doc.text(filter, 40, 110 + index * 15);
  });

  // ✅ Prepare table data
  const headers = [Object.keys(data[0])];
  const rows = data.map((row) => Object.values(row));

  // ✅ Create table with styling
  if (doc.autoTable) {
    doc.autoTable({
      head: headers,
      body: rows,
      startY: 160,
      styles: { fontSize: 10 },
      headStyles: { fillColor: [52, 73, 94], textColor: [255, 255, 255] },
      bodyStyles: { textColor: [0, 0, 0] },
      theme: "striped",
      didDrawPage: (data) => {
        doc.setFontSize(9);
        doc.text(
          `Generated by ERP Reporting Module | ${currentDate}`,
          40,
          doc.internal.pageSize.getHeight() - 20
        );
      },
    });
  } else {
    console.error("jspdf-autotable plugin not loaded.");
    alert("PDF generation failed. Please reinstall jspdf-autotable.");
    return;
  }

  // ✅ Save and log
  doc.save(`${selectedReport.name}_Report.pdf`);
  addLog(`Exported ${selectedReport.name} to PDF`);
};

  // 🔹 Real-time updates
  useEffect(() => {
    if (isRealTime && selectedReport) {
      const interval = setInterval(() => {
        generateFakeData(selectedReport, true);
        addLog(`Pulled live data for ${selectedReport.name}`);
      }, 5000);
      return () => clearInterval(interval);
    }
  }, [isRealTime, selectedReport]);

  // 🔹 Fake data generator (demo)
  const generateFakeData = (report, isRefresh = false) => {
    let newData = [];
    const now = new Date().toLocaleTimeString();

    switch (report.type) {
      case "sales":
        newData = Array.from({ length: 5 }, (_, i) => ({
          ID: i + 1,
          Product: `Product ${i + 1}`,
          Amount: (Math.random() * 10000).toFixed(2),
          Date: now,
        }));
        break;
      case "inventory":
        newData = Array.from({ length: 5 }, (_, i) => ({
          ID: i + 1,
          Item: `Item ${i + 1}`,
          Stock: Math.floor(Math.random() * 100),
          Date: now,
        }));
        break;
      case "finance":
        newData = Array.from({ length: 5 }, (_, i) => ({
          ID: i + 1,
          Category: ["Revenue", "Expense", "Profit"][i % 3],
          Value: (Math.random() * 5000).toFixed(2),
          Date: now,
        }));
        break;
      default:
        newData = [];
    }

    setData(newData);
    if (!isRefresh) addLog(`Data generated for ${report.name}`);
  };

  const addLog = (message) => {
    setLog((prev) => [message, ...prev].slice(0, 15));
  };

  // 🔹 Prevent data silos — auto-sync
  useEffect(() => {
    const autoSync = setInterval(() => {
      if (selectedReport) {
        generateFakeData(selectedReport, true);
        addLog(`Auto-synced data to prevent outdated reports`);
      }
    }, 15000);
    return () => clearInterval(autoSync);
  }, [selectedReport]);

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold text-gray-800">ERP Report Module</h1>

      {/* FILTERS */}
      <div className="bg-white p-4 rounded-lg shadow-md">
        <h2 className="font-medium mb-3">Customize Reports</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <input
            type="date"
            name="dateFrom"
            value={filters.dateFrom}
            onChange={handleFilterChange}
            className="border p-2 rounded"
          />
          <input
            type="date"
            name="dateTo"
            value={filters.dateTo}
            onChange={handleFilterChange}
            className="border p-2 rounded"
          />
          <select
            name="department"
            value={filters.department}
            onChange={handleFilterChange}
            className="border p-2 rounded"
          >
            <option>All</option>
            <option>Sales</option>
            <option>Finance</option>
            <option>Inventory</option>
          </select>
          <select
            name="region"
            value={filters.region}
            onChange={handleFilterChange}
            className="border p-2 rounded"
          >
             <option>All</option>
              <option>NCR</option>
              <option>Region I – Ilocos</option>
              <option>Region II – Cagayan Valley</option>
              <option>Region III – Central Luzon</option>
              <option>Region IV-A – CALABARZON</option>
              <option>Region V – Bicol Region</option>
              <option>Region VI – Western Visayas</option>
              <option>Region VII – Central Visayas</option>
              <option>Region VIII – Eastern Visayas</option>
              <option>Region IX – Zamboanga Peninsula</option>
              <option>Region X – Northern Mindanao</option>
              <option>Region XI – Davao Region</option>
              <option>Region XII – SOCCSKSARGEN</option>
              <option>CAR – Cordillera Administrative Region</option>
              <option>BARMM – Bangsamoro</option>
              <option>Region XIII – Caraga</option>
          </select>
        </div>
      </div>

      {/* REPORTS */}
      <div className="bg-white p-4 rounded-lg shadow-md">
        <h2 className="font-medium mb-3">Available Reports</h2>
        {reports.map((r) => (
          <div key={r.id} className="flex justify-between items-center border-b py-2">
            <span>{r.name}</span>
            <button
              onClick={() => handleGenerateReport(r)}
              className="bg-blue-600 text-white px-3 py-1 rounded"
            >
              Generate
            </button>
          </div>
        ))}
      </div>

      {/* TABLE PREVIEW */}
      <div className="bg-white p-4 rounded-lg shadow-md">
        <h2 className="font-medium mb-3">Report Preview</h2>
        {selectedReport ? (
          <>
            <Table reportType={selectedReport.type} data={data} />
            <div className="flex flex-wrap gap-2 mt-4">
              <button onClick={exportCSV} className="bg-green-500 text-white px-3 py-1 rounded">
                CSV
              </button>
              <button onClick={exportExcel} className="bg-yellow-500 text-white px-3 py-1 rounded">
                Excel
              </button>
              <button onClick={exportPDF} className="bg-red-500 text-white px-3 py-1 rounded">
                PDF
              </button>
            </div>
          </>
        ) : (
          <p className="text-gray-400">Select a report to display data.</p>
        )}
      </div>

      {/* REAL-TIME TOGGLE */}
      <div className="bg-white p-4 rounded-lg shadow-md">
        <label className="flex items-center gap-2">
          <input
            type="checkbox"
            checked={isRealTime}
            onChange={() => setIsRealTime(!isRealTime)}
          />
          <span>Enable Real-Time Data Retrieval</span>
        </label>
      </div>

      {/* SCHEDULING */}
      {selectedReport && (
        <div className="bg-white p-4 rounded-lg shadow-md">
          <h2 className="font-medium mb-3">Schedule Recurring Reports</h2>
          <div className="flex gap-2">
            <button
              onClick={() => scheduleReport("Daily")}
              className="bg-blue-500 text-white px-3 py-1 rounded"
            >
              Daily
            </button>
            <button
              onClick={() => scheduleReport("Weekly")}
              className="bg-blue-600 text-white px-3 py-1 rounded"
            >
              Weekly
            </button>
            <button
              onClick={() => scheduleReport("Monthly")}
              className="bg-blue-700 text-white px-3 py-1 rounded"
            >
              Monthly
            </button>
          </div>
        </div>
      )}

      {/* LOGS */}
      <div className="bg-white p-4 rounded-lg shadow-md">
        <h2 className="font-medium mb-3">System Logs</h2>
        <ul className="text-sm h-40 overflow-auto">
          {log.length === 0 ? (
            <li className="text-gray-400">No recent activity</li>
          ) : (
            log.map((l, i) => <li key={i}>• {l}</li>)
          )}
        </ul>
      </div>
    </div>
  );
}
